"use client";
import {useEffect,useState} from 'react';
import {AnimatedStage} from '@/components/animated-game';
import {Figure3D} from '@/components/figure-3d';
import {GameViewport} from '@/components/game-viewport';
import './game-shell.css';
import {ScanEye,Zap,ArrowRight,Check,RotateCw,GripVertical,Trophy,ArrowUp,ArrowDown,ShieldCheck,Trash2,BatteryCharging,WifiOff,TriangleAlert} from 'lucide-react';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle,DialogTrigger} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogAction,AlertDialogCancel,AlertDialogContent,AlertDialogDescription,AlertDialogFooter,AlertDialogHeader,AlertDialogTitle,AlertDialogTrigger} from '@/components/ui/alert-dialog';

import {missions,workflow,points,Answer} from '@/lib/game';

type Phase='welcome'|'entry'|'wheel'|'initial'|'decision'|'outcome'|'finish';
type Role='Installation'|'Ops'|'CPO';
type CompletedPlayer={id:number;name:string;company:string;role:Role;contact:string;score:number;createdAt:string};
const colors=['#ea3056','#e9542b','#cd7510','#953051','#60263f'];
const shuffled=['Grid Connection','Charger Installation','Site Survey','Commissioning','Civil Work','Go-Live','Electrical Installation'];
export default function Game(){
 const [phase,P]=useState<Phase>('welcome'),[name,N]=useState(''),[company,Co]=useState(''),[role,G]=useState<Role>('CPO'),[contact,C]=useState(''),[index,I]=useState(0),[choice,Q]=useState(''),[initial,J]=useState(''),[order,O]=useState(shuffled),[answers,A]=useState<Answer[]>([]),[vision,V]=useState(false),[power,U]=useState(3),[spin,S]=useState(false),[rotation,R]=useState(0),[pending,T]=useState<number|null>(null),[drag,D]=useState<number|null>(null),[saveState,B]=useState(''),[runId,H]=useState(''),[players,L]=useState<CompletedPlayer[]>([]),[playerPage,setPlayerPage]=useState(0),[installPrompt,setInstallPrompt]=useState<any>(null),[online,setOnline]=useState(true);
 const score=answers.reduce((t,a)=>t+points(a),0),m=missions[index],completed=answers.map(a=>a.scenario),available=missions.map((_,i)=>i).filter(i=>role==='Installation'?i===3:role==='Ops'?i!==3:true),remaining=available.filter(i=>!completed.includes(i));
 useEffect(()=>{if(!spin||pending===null)return;const timer=setTimeout(()=>{I(pending);Q('');J('');O([...shuffled]);V(false);S(false);T(null);P('initial');},2200);return()=>clearTimeout(timer)},[spin,pending]);
 async function loadPlayers(){try{const response=await fetch('/api/game-results');if(response.ok){const data=await response.json() as {players?:CompletedPlayer[]};L(data.players||[])}}catch{}}
 async function deletePlayer(id:number){try{const response=await fetch('/api/game-results?id='+id,{method:'DELETE'});if(!response.ok)throw new Error();L(players=>players.filter(player=>player.id!==id))}catch{window.alert('Unable to delete this player. Please try again.')}}
 useEffect(()=>{loadPlayers()},[]);
 useEffect(()=>{if('serviceWorker' in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{})},[]);
 useEffect(()=>{const onInstall=(event:Event)=>{event.preventDefault();setInstallPrompt(event)},onOnline=()=>setOnline(true),onOffline=()=>setOnline(false);setOnline(navigator.onLine);window.addEventListener('beforeinstallprompt',onInstall);window.addEventListener('online',onOnline);window.addEventListener('offline',onOffline);return()=>{window.removeEventListener('beforeinstallprompt',onInstall);window.removeEventListener('online',onOnline);window.removeEventListener('offline',onOffline)}},[]);
 useEffect(()=>{setPlayerPage(p=>Math.min(p,Math.max(0,Math.ceil(players.length/5)-1)))},[players.length]);
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();Promise.resolve(context.registerTool({name:'read_game_progress',description:'Read the current game stage, completed scenarios, points and remaining R-Vision charges. Does not return player contact details.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({stage:phase,completed:answers.length,score,charges:power})},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort()},[phase,answers.length,score,power]);
 function spinWheel(){if(spin||!remaining.length)return;const selected=remaining[Math.floor(Math.random()*remaining.length)];const target=(360-(selected*72+36))%360;R(rotation+1440+((target-rotation%360+360)%360));T(selected);S(true)}
 function playScenario(selected:number){if(!remaining.includes(selected)||spin)return;I(selected);Q('');J('');O([...shuffled]);V(false);P('initial')}
 function move(a:number,b:number){if(b<0||b>=order.length)return;const n=[...order];n.splice(b,0,n.splice(a,1)[0]);O(n)}
 function lockInitial(){J(index===3?order.join('|'):choice);P('decision')}
 function usePower(){if(power===0||vision)return;U(power-1);V(true)}
 function lockFinal(){A([...answers,{scenario:index,initial,final:index===3?order.join('|'):choice,vision}]);P('outcome')}
 async function finish(){P('finish');B('saving');try{const res=await fetch('/api/game-results',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,company,role,contact,answers,runId})});if(!res.ok)throw new Error();B('saved');loadPlayers()}catch{B('error')}}
 const restart=()=>{P('entry');N('');Co('');G('CPO');C('');A([]);U(3);V(false);Q('');B('');H('');R(0)};
 function exportPlayers(){const cell=(value:string|number)=>'"'+String(value??'').replaceAll('"','""')+'"';const rows=[['Name','Company','Role','Contact / email','Points','Completed at'],...players.map(p=>[p.name,p.company,p.role,p.contact,p.score,p.createdAt])];const blob=new Blob([rows.map(row=>row.map(cell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='r-one-player-scores.csv';a.click();URL.revokeObjectURL(url)}
 const installApp=async()=>{if(!installPrompt)return;installPrompt.prompt();await installPrompt.userChoice;setInstallPrompt(null)};
 const stats=<div className="stats"><div className="player-dashboard"><span className="player-name">{name || 'Operator'}</span><span className="player-contact">{role}{contact?' · '+contact:''}</span></div><span><Trophy size={17}/>{score} points</span><span className="power-count"><ScanEye size={19}/>{power}/3 charges</span></div>;
 const leaderboard=<Dialog><DialogTrigger asChild><button className="players-button" aria-label="View completed player scores"><Trophy size={16}/> Players <b>{players.length}</b></button></DialogTrigger><DialogContent className="players-modal"><DialogHeader><DialogTitle>Completed players</DialogTitle><DialogDescription>Name, company, role, optional contact and final score.</DialogDescription></DialogHeader><button className="export-players" onClick={exportPlayers} disabled={!players.length}>Export to Excel</button><div className="players-table">{players.length?players.slice(playerPage*5,playerPage*5+5).map(player=><div className="players-row" key={player.id}><span className="player-cell"><b>{player.name}</b><small>{player.company} · {player.role}</small></span><span>{player.contact||'No contact shared'}</span><b>{player.score} pts</b><AlertDialog><AlertDialogTrigger asChild><button className="delete-player" aria-label={'Delete '+player.name+'\'s result'}><Trash2 size={15}/><span>Delete</span></button></AlertDialogTrigger><AlertDialogContent size="sm"><AlertDialogHeader><AlertDialogTitle>Delete player data?</AlertDialogTitle><AlertDialogDescription>This permanently removes {player.name}’s saved result.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction className="confirm-delete" variant="destructive" onClick={()=>deletePlayer(player.id)}>Delete</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div>):<p className="no-players">No completed games yet.</p>}</div><div className="player-pagination"><button className="secondary" disabled={playerPage===0} onClick={()=>setPlayerPage(p=>p-1)}>Previous</button><span>{Math.min(playerPage+1,Math.max(1,Math.ceil(players.length/5)))} / {Math.max(1,Math.ceil(players.length/5))}</span><button className="secondary" disabled={(playerPage+1)*5>=players.length} onClick={()=>setPlayerPage(p=>p+1)}>Next</button></div></DialogContent></Dialog>;
 return <GameViewport><main><header><img src="/r-one-logo-clean.png" alt="R-One" width="105" height="41"/><span className="game-name">NETWORK COMMAND</span>{phase!=='welcome'&&phase!=='entry'&&stats}{!online&&<span className="offline-state">Offline</span>}{installPrompt&&<button className="install-button" onClick={installApp}>Install app</button>}{leaderboard}</header>
 {phase==='welcome'&&<section className="welcome"><Figure3D kind="buddy" className="welcome-buddy"/><div className="welcome-copy"><div className="eyebrow"><span className="beacon"/> NETWORK STATUS: LIVE</div><h1>YOUR CHARGING<br/>NETWORK<br/><em>JUST WENT LIVE.</em></h1><div className="launch-stats"><div><b>12</b><span>chargers.</span></div><div><b>4</b><span>locations.</span></div><div><b>1</b><span>operations team.</span></div></div><p className="incoming"><strong>And problems are already coming in.</strong></p><h2>Can you keep the network running?</h2><button className="primary" onClick={()=>P('entry')}>ENTER THE CONTROL ROOM <ArrowRight size={20}/></button><p className="support">Make decisions. Manage failures. Discover R-One.</p></div></section>}
 {phase==='entry'&&<section className="entry panel"><ScanEye className="large-icon"/><p className="eyebrow">OPERATOR CHECK-IN</p><h1>Take command.</h1><p>Your role sets the scenarios you can play. You can spin or choose one directly.</p><form onSubmit={e=>{e.preventDefault();const field=e.currentTarget.querySelector('input[name=contact]') as HTMLInputElement;const valid=!contact.trim()||/^[+0-9() .-]{7,25}$/.test(contact.trim())||/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(contact.trim());if(!valid){field.setCustomValidity('Enter a valid mobile number or email address');field.reportValidity();return;}H(Array.from(crypto.getRandomValues(new Uint8Array(18)),b=>b.toString(16).padStart(2,'0')).join(''));if(role==='Installation'){I(3);Q('');J('');O([...shuffled]);V(false);P('initial')}else P('wheel')}}><label>Name<input required maxLength={120} value={name} onChange={e=>N(e.target.value)} autoComplete="name" placeholder="Your name"/></label><label>Company name<input required maxLength={160} value={company} onChange={e=>Co(e.target.value)} autoComplete="organization" placeholder="Company name"/></label><label>Role<select value={role} onChange={e=>G(e.target.value as Role)}><option value="Installation">Installation team</option><option value="Ops">Ops team</option><option value="CPO">CPO</option></select></label><label>Contact number or email <span>(optional)</span><input name="contact" maxLength={120} value={contact} onChange={e=>{e.target.setCustomValidity('');C(e.target.value)}} placeholder="Mobile number or work email" title="Enter a valid mobile number or email address"/></label><p className="notice">Your name, company, role, optional contact and score will be saved when you finish.</p><button className="primary">Continue <ArrowRight size={18}/></button></form></section>}
 {phase==='wheel'&&<section className="wheel-layout"><div><p className="eyebrow">{role.toUpperCase()} CONTROL ROOM / {answers.length} OF {available.length} PLAYED</p><h1>What’s your<br/><em>next challenge?</em></h1><p>Spin for a random challenge, or choose one from your role’s scenario list.</p><div className="wheel-actions"><button className="primary" disabled={spin||!remaining.length} onClick={spinWheel}><RotateCw size={19} className={spin?'spinning':''}/>{spin?'Selecting your scenario…':'SPIN THE WHEEL'}</button>{answers.length>0&&<button className="secondary" disabled={spin} onClick={finish}>Finish & save score</button>}</div><p className="small">20 points per scenario · No repeats · No time pressure</p><div className="mission-list">{available.map(i=>{const s=missions[i],played=completed.includes(i);return <button key={s.name} type="button" disabled={played||spin} className={played?'played':''} onClick={()=>playScenario(i)}><span>{played?<Check size={16}/>:String(i+1).padStart(2,'0')}</span>{s.name}{played?<b>{points(answers.find(a=>a.scenario===i)!)} pts</b>:<em>Play</em>}</button>})}</div></div><div className="wheel-area"><div className="pointer"/><div className="wheel" style={{transform:`rotate(${rotation}deg)`,background:`conic-gradient(${colors.map((c,i)=>`${!available.includes(i)||completed.includes(i)?'#77747d':c} ${i*72}deg ${(i+1)*72}deg`).join(',')})`}}>{missions.map((s,i)=>{const angle=(i*72+36)*Math.PI/180;return <span className="wheel-label" key={s.name} style={{left:`${50+31*Math.sin(angle)}%`,top:`${50-31*Math.cos(angle)}%`,transform:`translate(-50%,-50%) rotate(${-rotation}deg)`}}>{!available.includes(i)?'— ':completed.includes(i)?'✓ ':''}{s.name}</span>})}<button type="button" className="wheel-center" aria-label="Spin the wheel" onClick={spinWheel} disabled={spin||!remaining.length}><Zap size={34}/></button></div><p className="small">Grey sectors are outside your role or already completed.</p></div></section>}
 {(phase==='initial'||phase==='decision')&&<AnimatedStage index={index} phase={phase} choice={choice} onChoice={Q} vision={vision} power={power} onPower={usePower} onLock={phase==='initial'?lockInitial:lockFinal} onBack={()=>P('wheel')} order={order} onMove={move}/>}
 {phase==='outcome'&&(()=>{const earned=points(answers[answers.length-1]),right=earned===20;return <section className={'outcome panel '+(right?'is-correct':'is-wrong')}><Figure3D kind="buddy" celebrate={right} className="outcome-buddy"/>{right&&<div className="celebration" aria-hidden="true">{Array.from({length:16},(_,i)=><i key={i} style={{left:(i*6+2)+'%',animationDelay:(i%5)*.15+'s',background:['#eb3156','#fa9832','#38c9bd'][i%3]}}/>)}</div>}<div className="round-points"><ShieldCheck/>{earned} / 20 points <b>{right?'CORRECT':'NEEDS A RETHINK'}</b></div><p className="eyebrow">ROUND COMPLETE / {m.name.toUpperCase()}</p><h1>“{m.quote}”</h1><p>{right?m.outcome:'That was a reasonable first call, but it was not the choice with the greatest network impact. Use the reveal to see why.'}</p>{index===3&&<p className="sequence">{workflow.join(' → ')}</p>}<div className="wheel-actions">{remaining.length>0&&<button className="primary" onClick={()=>P('wheel')}>Back to the wheel <RotateCw size={18}/></button>}<button className={remaining.length?'secondary':'primary'} onClick={finish}>Finish & save score</button></div><p className="small">{score} points earned · {answers.length} scenarios played · {power} power-ups remaining</p></section>})()}
 {phase==='finish'&&<section className="finish panel"><div className="finish-heading"><div><p className="eyebrow">{name.toUpperCase()} / MISSION REPORT</p><h1>In a game, you can <em>guess and learn.</em> In your network, every call counts.</h1></div><div className="score-card"><span>YOUR SCORE</span><div className="final-score">{score}<small>/ {answers.length*20}</small></div></div></div><div className="finish-dashboard"><div className="finish-report"><div className="report">{answers.map(a=><div key={a.scenario}><span>{missions[a.scenario].name}</span><span>{a.vision?'R-Vision used':'Unassisted'}</span><b>{points(a)}/20</b></div>)}</div></div><div className="finish-actions"><div aria-live="polite" className="save-status">{saveState==='saving'?'Saving your result…':saveState==='saved'?'Score saved':'Save failed'}</div>{saveState==='error'&&<button className="primary" onClick={finish}>Retry saving</button>}<button className="primary" disabled={saveState!=='saved'} onClick={restart}>Play again <RotateCw size={17}/></button></div></div></section>}
 <footer>R-ONE: NETWORK COMMAND <span>Interactive demo · Simulated operational data</span></footer></main></GameViewport>
}
