"use client";
import {useState} from 'react';
import {ScanEye,RotateCcw,Check,LockKeyhole,ArrowRight,ArrowLeft,GripVertical,Activity,CalendarCheck,Power,Clock,WifiOff,Flag,PlugZap,Search,Construction,Cable} from 'lucide-react';
import {missions,workflow} from '@/lib/game';
import {Figure3D} from './figure-3d';
import './animated-game.css';
const intros=['One technician. Two faults. Tap the charger you would repair first.','Three chargers. Which one would you trust with the next customer?','17 alerts or 5? Tap the charger that needs attention.','Build your station! Drag the cards into order, or use the arrows.','All three work today. Tap the charger you would investigate.'];
const reveals=['A is busier and more critical. Send your technician where the impact is highest!','Charger A is the healthy choice. Charger C is available, but repeated failed attempts are reducing its success rate and energy delivered.','A recovers in seconds. B interrupts charging for minutes. Fewer alerts can hurt more!','Build on the right foundations. Complete each dependency before the next activity!','C shows a worsening pattern. Investigate it before it fails!'];
const stageIcons=[Search,Construction,Cable,PlugZap,Power,Check,Flag];
type Props={index:number;phase:string;choice:string;onChoice:(s:string)=>void;vision:boolean;power:number;onPower:()=>void;onLock:()=>void;onBack:()=>void;order:string[];onMove:(a:number,b:number)=>void};
export function AnimatedStage(p:Props){
 const {index,phase,choice,onChoice,vision,power,onPower,onLock,onBack,order,onMove}=p;
 const [replay,setReplay]=useState(0),[drag,setDrag]=useState<number|null>(null);
 const line=vision?reveals[index]:phase==='decision'?(power?'First choice locked! Want my help? Use R-Vision, then make your final call.':'First choice locked! Review your choice and make your final call.'):intros[index];
 const selectChargers=index===0||index===1||index===2||index===4;
 const ids=index===1||index===4?['A','B','C']:['A','B'];
 const badge=(i:number)=>index===0?['Connector fault','Rectifier fault'][i]:index===1?['Available','Faulted','Available'][i]:index===2?['17 alerts','5 alerts'][i]:['72% utilisation','68% utilisation','75% utilisation'][i];
 const detail=(i:number)=>index===0?['Highway restaurant · 10 min ago','City hub · 25 min ago'][i]:index===1?['10 kWh delivered in last 7 days','Unavailable','50 kWh delivered in last 7 days'][i]:index===2?'Communication errors · 24 hours':['No critical alert','1 minor communication alert','2 minor alerts'][i];
 return <section className={'animated-stage scenario-'+index}>
  <div className="stage-heading"><button className="replay-button" onClick={onBack}>← Back to wheel</button><div><span className="stage-kicker">{missions[index].name.toUpperCase()}</span><h1>{missions[index].title}</h1></div></div>
  <div className="buddy-dock buddy-top"><Figure3D kind="buddy" scanning={vision} celebrate={!!choice} className="buddy-figure"/><div className="buddy-dialogue" key={line}><span>R-ONE BUDDY</span><p aria-live="polite">{line}</p>{vision&&<button className="replay-button" onClick={()=>setReplay(n=>n+1)}><RotateCcw size={14}/>Replay insights</button>}</div><div className="decision-controls">{phase==='decision'&&!vision&&power>0&&<button className="vision-trigger" onClick={onPower}><ScanEye size={20}/>USE R-VISION <small>−1 charge</small></button>}<button className="lock-scene" disabled={index!==3&&!choice} onClick={onLock}><LockKeyhole size={18}/>{phase==='initial'?'LOCK MY CHOICE':'LOCK FINAL ANSWER'}</button></div></div>
  <div className={'play-world '+(vision?'vision-on':'')}>
   <div className="world-label"><span>{index===3?'BUILD ZONE':'LIVE NETWORK'}</span><span>{vision?'INTELLIGENCE REVEALED':index===3?'7 ACTIVITIES':selectChargers?'TAP A CHARGER TO SELECT':'MAKE YOUR CALL'}</span></div>
   {index!==3?<div className={'charger-line chargers-'+ids.length}>{ids.map((id,i)=><button type="button" aria-label={'Charger '+id+'. '+badge(i)+'. '+detail(i)} aria-pressed={choice===id} disabled={!selectChargers} onClick={()=>onChoice(id)} key={id} className={'charger-object '+(choice===id?'chosen ':'')+(vision?'revealed ':'')}>
    <span className={'floating-alert '+(index===1?(i===1?'faulted':'healthy'):'')}>{index===2?<WifiOff size={18}/>:<Activity size={18}/>} {badge(i)}</span>
    <div className="charger-sprite"><Figure3D kind="charger" active={choice===id} scanning={vision}/><span className="selection-ring">{choice===id?<Check size={22}/>:id}</span></div>
    <strong>CHARGER {id}</strong><small>{detail(i)}</small>
    {vision&&index===0&&<div className="impact-meter" key={replay}><b>{i===0?'92%':'34%'} utilisation</b><span><i style={{width:i===0?'92%':'34%'}}/></span><small>{i===0?'HIGH severity · HIGH criticality':'MEDIUM severity · MEDIUM criticality'}</small></div>}
    {vision&&index===2&&<div className="duration-meter" key={replay}><b>{i===0?'8 sec average downtime per alert':'14 min average downtime per alert'}</b><div className={'duration-track '+(i===0?'quick':'slow')}><i/></div><small>{i===0?'Auto-recovered · longest 21 sec':'Sessions interrupted · longest 31 min'}</small></div>}
    {vision&&index===4&&<span className={'risk-tag '+(i===2?'risk-high':'')}>{i===2?'HIGH RISK · NEXT 7 DAYS':'No flagged pattern'}</span>}
   </button>)}</div>:<><ol className="build-track">{order.map((s,i)=>{const Icon=stageIcons[workflow.indexOf(s)];return <li key={s} className={drag===i?'dragging':''} draggable onDragStart={()=>setDrag(i)} onDragEnd={()=>setDrag(null)} onDragOver={e=>e.preventDefault()} onDrop={()=>{if(drag!==null)onMove(drag,i);setDrag(null)}}><div><b>STEP {i+1}</b><GripVertical size={17}/></div><Icon size={38}/><strong>{s}</strong><nav><button aria-label={'Move '+s+' earlier'} disabled={i===0} onClick={()=>onMove(i,i-1)}><ArrowLeft size={18}/></button><button aria-label={'Move '+s+' later'} disabled={i===6} onClick={()=>onMove(i,i+1)}><ArrowRight size={18}/></button></nav></li>})}</ol><div className="dependency-path">{vision?<div className="dependency-insights"><div><b>01 · Start right</b><span>Site survey confirms the layout, power capacity and civil scope before work begins.</span></div><div><b>02 · Build before install</b><span>Complete civil work before installing the charger.</span></div><div><b>03 · Prove before launch</b><span>Electrical installation and grid connection enable commissioning; successful commissioning unlocks go-live.</span></div></div>:<span>Drag the activity cards into the order you would use on site.</span>}</div></>}
   {vision&&index===1&&<div className="session-replay" key={replay}><b>CHARGER C / LAST 7 DAYS</b><div>{[true,false,true,true,false,true,false,true,true,false,true,false,true,false,true,true,false,true].map((failed,i)=><span style={{animationDelay:i*.08+'s'}} className={failed?'failed':'passed'} key={i}>{failed?'×':'✓'}</span>)}</div><p><strong>11 failed attempts</strong> <b>91% → 39% success</b> <span>64 kWh → 50 kWh delivered</span></p></div>}
   {vision&&index===4&&<div className="signal-timeline" key={replay}>{['14 days ago · Signal drops','11 days ago · Failed sessions','9 days ago · Power fluctuation','7 days ago · More reboots','5 days ago · Abnormal sessions','3 days ago · Signal degradation'].map((x,i)=><span key={x} style={{animationDelay:i*.16+'s'}}>{x}</span>)}</div>}
  </div>
 </section>
}
