export const workflow = ['Site Survey','Civil Work','Electrical Installation','Charger Installation','Grid Connection','Commissioning','Go-Live'];
export type Answer = { scenario:number; initial:string; final:string; vision:boolean };
export const correctAnswers=['A','C','B',workflow.join('|'),'C'];
export function points(a:Answer){return a.final===correctAnswers[a.scenario]?20:0;}
export const missions=[
 {name:'Fault triage',title:'Prioritise the failure',question:'One technician. Two faults. Where do you send them?',brief:'Choose using the information below. Lock your initial decision to continue.',cards:[['Charger A','Connector gun issue','Highway Restaurant · Alert 10 minutes ago'],['Charger B','Rectifier issue','City Charging Hub · Alert 25 minutes ago']],options:[['A','Prioritise Charger A'],['B','Prioritise Charger B']],insights:[['Charger A','92% utilisation','High severity · High criticality'],['Charger B','34% utilisation','Medium severity · Medium criticality']],quote:'Don’t prioritise the fault. Prioritise the impact.',outcome:'Dispatch to Charger A first. Its higher utilisation, severity and criticality put more of the network at risk. Charger B remains queued for attention.'},
 {name:'Session health',title:'Which charger is actually healthy?',question:'Choose the charger you would trust with the next customer.',brief:'Two chargers look available. Look closely at what they have delivered.',cards:[['Charger A','Available · 10 kWh','Delivered in the last 7 days'],['Charger B','Faulted','Unavailable'],['Charger C','Available · 50 kWh','Delivered in the last 7 days']],options:[['A','Choose Charger A'],['B','Choose Charger B'],['C','Choose Charger C']],insights:[['Charger A','18 attempts · 11 failed','Success rate fell from 91% to 39% in 7 days'],['Energy delivered','64 kWh → 50 kWh','Fewer successful sessions, despite Available status']],quote:'Available is a status. Healthy is a customer outcome.',outcome:'Choose Charger C. Charger A looks available but its low delivery is driven by repeated failed attempts and a sharply falling success rate.'},
 {name:'Alert impact',title:'The repeated alert',question:'Which charger requires greater attention?',brief:'The same communication error appeared on two chargers in the last 24 hours.',cards:[['Charger A','17 occurrences','Communication error'],['Charger B','5 occurrences','Communication error']],options:[['A','Investigate Charger A'],['B','Investigate Charger B']],insights:[['Charger A','8-second average','Longest: 21 seconds · Auto-recovered every time'],['Charger B','14-minute average','Longest: 31 minutes · Charging sessions interrupted']],quote:'Frequency tells you how often. Duration tells you how much it hurts.',outcome:'Investigate Charger B first. Fewer events caused much longer disruption and interrupted charging sessions.'},
 {name:'Station build',title:'Build the charging station',question:'Can you get this station ready for go-live?',brief:'Drag the activities into the expected sequence for this project, or use the move buttons.',cards:[],options:[],insights:[['Installation dependency','Civil Work → Charger Installation','Prepare the site before installing the charger'],['Commissioning gates','Electrical Installation + Grid Connection','Both must be ready before commissioning'],['Go-live gate','Commissioning → Go-Live','Commission before opening the station']],quote:'Turn an installation process into a repeatable, dependency-driven workflow.',outcome:'R-One configures the sequence and its dependencies so the process can be reused across projects. This is the expected sequence for this demo project.'},
 {name:'Failure prediction',title:'Predict the failure',question:'Which charger would you investigate before it fails?',brief:'All three chargers are operational. Make an initial choice, then decide how to act.',cards:[['Charger A','72% utilisation','Available · No critical alert'],['Charger B','68% utilisation','Available · 1 minor communication alert'],['Charger C','75% utilisation','Available · 2 minor alerts']],options:[['A','Investigate Charger A'],['B','Investigate Charger B'],['C','Investigate Charger C']],insights:[['Charger C','High predicted failure risk','Within the next 7 days — simulated forecast'],['Degradation pattern','Multiple signals worsening together','Communication, session behaviour, power and reboots']],quote:'The best failure is the one your customer never experiences.',outcome:'Schedule a preventive intervention for Charger C. A planned response addresses the issue before customers encounter an unexpected outage.'}
];
